### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by npetryk** [codeivate/codeivate-st#1]
Hey, I think Codeivate is a pretty neat idea. Unfortunately, I do most of my coding at work and if anything other than my web browsers want to make a call to the outside, it needs to go through a proxy.

I was looking through the repo to see if I could add it myself but all of the plugin files are compiled. What gives?

**Comment by p4ul** [comment]
Hi matrix10657,
The files are mainly compiled to try and keep some integrity in the system, otherwise you can basically modify one variable while running the IDE and every action you perform would become 9000 actions, making it impossible to provide any kind of comparison between users. I know compiling them won't stop everybody (and I have code to detect this on the server) but I'm hoping that it will provide enough of a discouragement to stop people "accidentally" messing round with it.  I do plan on re-factoring it so only 1 or 2 modules are shipped compiled and all the other non essential ones such as uploading info to the server, growl, notify-send support etc would become open sourced :)

**Comment by leodido** [comment]
I'have the same problem: I do a lot of my work behind a proxy.
You could add support for "http_proxy" and "https_proxy" sublime text options (e.g, as package control does). Another possible option could possibly be to store data in an encrypted file and upload this file to the codeivate server ..
These are just ideas.

**Comment by p4ul** [comment]
Hi,

I found this article

http://stackoverflow.com/questions/16936165/unable-to-configure-python-to-proxy

For Windows 7:

Right click on Computer, and select Properties
On the left, select Advanced system settings
Click on the Advanced tab, then click Environment Variables
Click on New.. under User Variables
In Variable name, type HTTP_PROXY and in Variable value, typehttp://username:password@proxy.com:port (where proxy.com is the hostname or IP address of your proxy, and port is the port for it - grab it from Internet Explorer)
Click OK, then OK, then OK again to dismiss all the dialog boxes.

But I haven't tested it, I also have heard that someone set a system level proxy on Ubuntu and it works.

**Comment by leodido** [comment]
I have Ubuntu 13.04 with a system level proxy and it does not work.

This is what ST3 say:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "X/urllib/request.py", line 1252, in do_open
  File "X/http/client.py", line 1049, in request
  File "X/http/client.py", line 1087, in _send_request
  File "X/http/client.py", line 1045, in endheaders
  File "X/http/client.py", line 890, in _send_output
  File "X/http/client.py", line 828, in send
  File "X/http/client.py", line 806, in connect
  File "X/socket.py", line 406, in create_connection
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "/home/paul/.config/sublime-text-3/Packages/codeivate/codeivated/ActivityMonitor.py", line 290, in run
  File "X/urllib/request.py", line 160, in urlopen
  File "X/urllib/request.py", line 473, in open
  File "X/urllib/request.py", line 491, in _open
  File "X/urllib/request.py", line 451, in _call_chain
  File "X/urllib/request.py", line 1272, in http_open
  File "X/urllib/request.py", line 1255, in do_open
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>
```

This line is very strange:

`File "/home/paul/.config/sublime-text-3/Packages/codeivate/codeivated/ActivityMonitor.py", line 290, in run`.

**Comment by dibs** [comment]
I have the same issue.
Just tried adding the proxy var to windows environment vars and am still getting the same as @leodido.

**Comment by p4ul** [comment]
@dibs I thought you had it working in Ubuntu?

**Comment by dibs** [comment]
@p4ul I have it working great on Ubuntu on my laptop but at work on my Win7 machine I am still getting proxy issues.

**Comment by npetryk** [comment]
I have never been able to get the win7 system-wide proxy settings to work (@ work)

**Comment by rudym** [comment]
Very upsetting, 4 months and the issue still not resolved.

mb in project should be implemented some lines like explaned here http://stackoverflow.com/questions/16703936/proxy-connection-with-python

**Comment by p4ul** [comment]
Hi rudym, 
Sorry about the delay in getting this resolved. I will make it a top priority.

**Comment by p4ul** [comment]
I have moved the network code into Network.py and added some better proxy support

Available in https://github.com/codeivate/codeivate-st/tree/sublime3-dev

It should be ready for testing.

**Comment by rudym** [comment]
Thank you @p4ul 

For now it generates me WinError 10060 mesages that I've put here https://gist.github.com/rudym/7465082  (too big for a comment)

**Comment by p4ul** [comment]
Thanks, I will refactor it to use the python requests library and see if that does the trick.

**Comment by p4ul** [comment]
I have modified the Network.py file to use the requests module http://www.python-requests.org/

Make sure you have updated from the sublime3-dev branch then

In the Preferences -> Package Settings -> Codeivate -> Settings - user  settings file try setting something like

```
"proxies":
{
    "http": "http://10.10.1.10:3128",
    "https": "https://10.10.1.10:1080"
},
```

or with auth

```
"proxies":
{
    "http": "http://user:pass@10.10.1.10:3128",
    "https": "https://user:pass@10.10.1.10:1080"
},
```

**Comment by rudym** [comment]
```
using proxy for http://www.codeivate.com/API/index.php
{'http': 'http://127.0.0.1:8080', 'https': 'https://127.0.0.1:8080'}
RESPONSE
<Response [200]>
```

My congratulations! You did it!

It will not work with proxy server from Microsoft though, because of its ntlm authentication. 
This can be overstepped by using local proxy with ntlm auth, like http://cntlm.sourceforge.net/

**Comment by p4ul** [comment]
@rudym Yessss! at last :smile:

**Comment by rudym** [comment]
@p4ul He-Man at work! )) :+1:

**Comment by cagi23** [comment]
Hi this is my configuration file

{
    "dialog": false,
    "growl_active": true,
    "machine_name":
    {
        "345052807176": "change_me"
    },
    "notify_send_active": true,
    "notify_send_path": "/usr/bin/notify-send",
    "proxies":
    {
        "http": "http://192.168.10.12:8080"
    },
    "pushover_active": false,
    "pushover_user_id": "",
    "user_id": "test",
    "user_token": "test"
}

but does  not works.

How can I fix this issue ?

**Comment by p4ul** [comment]
@carloDev are you getting any errors in the console?

**Comment by cagi23** [comment]
I have this error:
[Errno 10061] Unable to establish connection. Persistent refusal of the target computer
Network Error:
<attribute 'message' of 'exceptions.BaseException' objects>
Listener Started

**Comment by p4ul** [comment]
So I did a bit of googling and it seems like it could be caused by either your firewall blocking the application connecting to http://192.168.10.12:8080 or http://192.168.10.12:8080 not being accessible from that machine?

Is there any firewall programs running on your machine? have you checked (Windows?) firewall?

If you go to cmd.exe and run "netstat -a" can you see 192.168.10.12:8080 LISTENING?

**Comment by cagi23** [comment]
I can't see 92.168.10.12:8080 from the "netstat -a" command. I have also tried to insert username and password in this way "http://username:password@proxy.com:port" but does not works. With the Intellij's plugin I don't have this problem.
