### ISSUE TITLE
NameError: global name 'Pref' is not defined

### ISSUE THREAD

**Issue by leodido** [codeivate/codeivate-st#2]
When codeivate posts data there is this error in the ST3 console:

```
posting data for R
message :+1 Focus 
icon base :--icon=/home/leodido/.config/sublime-text-3/Packages/codeivate-st/codeivated/icons/32x32/
Exception in thread Thread-75:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "C:\Users\Paul\AppData\Roaming\Sublime Text 3\Packages\codeivate-st\codeivated\FeedBack.py", line 110, in run
NameError: global name 'Pref' is not defined
```

**Note**: ubuntu 13.04 x86

**Comment by p4ul** [comment]
Hi @leodido,
Thanks for reporting this.
I have a new ST3 version that is up for testing that has some new features and should fix this problem 
details http://www.screenr.com/wGXH install from  https://github.com/codeivate/codeivate-st/tree/st3-dev

Cheers,
- Paul

**Comment by leodido** [comment]
~~Installed: no more that error ! It works like a charm, thanks.~~

@p4ul retrofront, again:

```
{'success': ['great success! [...]']}
posting data for R
message :+1 R
icon base :--icon=/home/leodido/.config/sublime-text-3/Packages/codeivate-st/codeivated/icons/32x32/
Exception in thread Thread-1112:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "C:\Users\Paul\AppData\Roaming\Sublime Text 3\Packages\codeivate-st\codeivated\FeedBack.py", line 110, in run
NameError: global name 'Pref' is not defined
```

**Comment by p-j** [comment]
Got this too : 

```
posting data for JavaScript
message :streak ended 2 mins  JavaScript
icon base :--icon=/home/jeremie/.config/sublime-text-3/Packages/codeivate-st/codeivated/icons/32x32/
Exception in thread Thread-744:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "C:\Users\Paul\AppData\Roaming\Sublime Text 3\Packages\codeivate-st\codeivated\FeedBack.py", line 110, in run
NameError: global name 'Pref' is not defined

{'success': ['great success! [12|158229828540]']}
```

I'm running build 3059

**Comment by p4ul** [comment]
Hi p-j,
Did you try running from  https://github.com/codeivate/codeivate-st/tree/st3-dev branch?

**Comment by p-j** [comment]
I'm using [Package Control](https://sublime.wbond.net/packages/Codeivate) to install, and after looking inside the `Codeivate.sublime-package` the `READ ME` is the same as you're st3-dev branch

**Comment by p4ul** [comment]
Thanks, this wont effect the data being passed up to the server 

I think this is a bug with growl notifications It should go away if you set "growl_active": false, in your config.

I will fix it next release :)

**Comment by czettnersandor** [comment]
Still there, very annoying:

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "C:\Users\Paul\AppData\Roaming\Sublime Text 3\Packages\codeivate-st\codeivated\FeedBack.py", line 110, in run
NameError: global name 'Pref' is not defined
```

**Comment by ryukinix** [comment]
That problem it's very annoying. Here it's the same. 

**Nobody have some idea to fix this?** I am will thinking quitting to use codeivate-st on my Sublime Text3, this bug made a conflict with a SublimeGit on `git push`. Serious, that issue was found a 3 years ago... **it's really so hard to fix it**? I did try to search something on the repository, but i just found the **bytecodes**. Where is the source code? If you don't work more in this repository, think in the possibility to make the software a really open-source for other contributors help you and the community whose still are using the bugged plugin : (

I'm very sad with that, sorry me for this words.

**Comment by czettnersandor** [comment]
My summary (on the website) is now a white screen, perhaps a PHP error. Not sure where to report, so I switched to [WakaTime](https://wakatime.com/), much better and works.

**Comment by ryukinix** [comment]
I will do that too! Codeivate it's now a lot of bugs. :disappointed:
